# Generated by Django 4.0.4 on 2022-11-29 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('line_id', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashflowState', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ship_fee', models.IntegerField(default=0, null=True)),
                ('orderMoney', models.IntegerField(default=0, null=True)),
                ('prisoner_name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('prisoner_id', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('memo', models.TextField(blank=True, default='', null=True)),
                ('paymentType', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ATMInfoBankCode', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ATMInfovAccount', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ATMInfoExpireDate', models.DateTimeField(blank=True, null=True)),
                ('ATMFiveDigit', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('CVSInfoPaymentNo', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('CVSInfoPaymentURL', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('CVSInfoExpireDate', models.DateTimeField(blank=True, null=True)),
                ('createDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('isPublish', models.BooleanField(blank=True, default=True, null=True)),
                ('info', models.TextField(blank=True, default='', null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('stocks', models.IntegerField(blank=True, default=0, null=True)),
                ('week_sum_nums', models.IntegerField(blank=True, default=0, null=True)),
                ('week_sum_revenue', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.category')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisionOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrderShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, null=True)),
                ('money', models.IntegerField(default=0, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='suppervisionOffice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.supervisionoffice'),
        ),
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(blank=True, default=0, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentType', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('MerchantID', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('OrderInfoMerchantTradeNo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('OrderInfoTradeDate', models.DateTimeField(null=True)),
                ('OrderInfoTradeNo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('OrderInfoTradeAmt', models.IntegerField(default=0, null=True)),
                ('OrderInfoPaymentType', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('OrderInfoChargeFee', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('OrderInfoTradeStatus', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ATMInfoBankCode', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ATMInfovAccount', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ATMInfoExpireDate', models.DateTimeField(null=True)),
                ('CVSInfoPayFrom', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('CVSInfoPaymentNo', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('CVSInfoPaymentURL', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('CardInfoAuthCode', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('CardInfoGwsr', models.IntegerField(default=0, null=True)),
                ('CardInfoProcessDate', models.DateTimeField(null=True)),
                ('CardInfoAmount', models.IntegerField(default=0, null=True)),
                ('CardInfoCard6No', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('CardInfoCard4No', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='modelCore.orderstate'),
        ),
        migrations.AddField(
            model_name='order',
            name='supervisionOffice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='modelCore.supervisionoffice'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('isPublish', models.BooleanField(blank=True, default=True, null=True)),
                ('info', models.TextField(blank=True, default='', null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('stocks', models.IntegerField(blank=True, default=0, null=True)),
                ('week_sum_nums', models.IntegerField(blank=True, default=0, null=True)),
                ('week_sum_revenue', models.IntegerField(blank=True, default=0, null=True)),
                ('suppervisionOffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.supervisionoffice')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='suppervisionOffice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.supervisionoffice'),
        ),
    ]
