# Generated by Django 4.0.4 on 2022-12-01 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0002_meal_code_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealOrderShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, null=True)),
                ('money', models.IntegerField(default=0, null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.meal')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='petty_cash',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='PettyCash',
        ),
        migrations.AddField(
            model_name='mealordership',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.order'),
        ),
    ]
