# Generated by Django 4.0.1 on 2022-04-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0002_auto_20220426_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
