# Generated by Django 4.0.4 on 2022-04-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
