# Generated by Django 4.0.4 on 2023-01-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0003_mealordership_order_petty_cash_delete_pettycash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iOS_current_version', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('android_current_version', models.CharField(blank=True, default='', max_length=10, null=True)),
            ],
        ),
    ]
