# Generated by Django 4.0.4 on 2023-01-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0004_appversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appversion',
            name='iOS_current_version',
        ),
    ]
