# Generated by Django 4.0.4 on 2022-04-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0004_user_line_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_gotten_line_id',
            field=models.BooleanField(default=False),
        ),
    ]
