# Generated by Django 4.0.4 on 2022-04-28 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0005_user_is_gotten_line_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_gotten_line_id',
        ),
    ]
