# Generated by Django 4.0.4 on 2022-05-11 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0006_remove_user_is_gotten_line_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='modelCore.product'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
