# Generated by Django 4.0.4 on 2023-01-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0007_order_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
