# Generated by Django 4.0.4 on 2022-05-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0007_order_amount_order_product_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sublabel',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
