# Generated by Django 4.0.4 on 2022-05-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0008_product_stock_product_sublabel_product_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='stocks',
        ),
    ]
