# Generated by Django 4.0.4 on 2023-01-04 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0008_order_is_urgent_user_line_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsideProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('isPublish', models.BooleanField(blank=True, default=True, null=True)),
                ('info', models.TextField(blank=True, default='', null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('stocks', models.IntegerField(blank=True, default=0, null=True)),
                ('week_sum_nums', models.IntegerField(blank=True, default=0, null=True)),
                ('week_sum_revenue', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.category')),
                ('suppervisionOffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.supervisionoffice')),
            ],
        ),
        migrations.CreateModel(
            name='OutsideProductOrderShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, null=True)),
                ('money', models.IntegerField(default=0, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.order')),
                ('outside_product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.outsideproduct')),
            ],
        ),
    ]
