# Generated by Django 4.0.4 on 2023-02-06 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0010_remove_outsideproduct_category_outsidecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productordership',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelCore.product'),
        ),
    ]
