# Generated by Django 4.0.4 on 2023-03-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0011_alter_productordership_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('create_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATMInfoBankCode', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('ATMInfovAccount', models.CharField(blank=True, default='', max_length=35, null=True)),
            ],
        ),
    ]
