# Generated by Django 4.0.4 on 2023-03-14 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0012_announcement_configdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('isPublish', models.BooleanField(blank=True, default=True, null=True)),
                ('isSpicy', models.BooleanField(blank=True, default=False, null=True)),
                ('info', models.TextField(blank=True, default='', null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('stocks', models.IntegerField(blank=True, default=0, null=True)),
                ('week_sum_nums', models.IntegerField(blank=True, default=0, null=True)),
                ('week_sum_revenue', models.IntegerField(blank=True, default=0, null=True)),
                ('suppervisionOffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.supervisionoffice')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialMealOrderShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, null=True)),
                ('money', models.IntegerField(default=0, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.order')),
                ('special_meal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.specialmeal')),
            ],
        ),
    ]
