# Generated by Django 4.0.4 on 2023-03-22 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0015_specialmealship_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialmeal',
            name='info',
        ),
        migrations.RemoveField(
            model_name='specialmeal',
            name='price',
        ),
        migrations.RemoveField(
            model_name='specialmeal',
            name='stocks',
        ),
        migrations.RemoveField(
            model_name='specialmeal',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='specialmeal',
            name='week_sum_nums',
        ),
        migrations.RemoveField(
            model_name='specialmeal',
            name='week_sum_revenue',
        ),
    ]
