# Generated by Django 4.0.4 on 2022-05-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0016_remove_order_product_productordership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.AddField(
            model_name='productordership',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
