# Generated by Django 4.0.4 on 2022-05-19 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0017_remove_order_amount_productordership_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productordership',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='modelCore.orderstate'),
        ),
    ]
