# Generated by Django 4.0.4 on 2023-03-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0017_alter_meal_suppervisionoffice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialmeal',
            name='isSpicy',
        ),
        migrations.AddField(
            model_name='specialmealship',
            name='isSpicy',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
