# Generated by Django 4.0.4 on 2022-05-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0018_productordership_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='week_sum_nums',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='week_sum_revenue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
