# Generated by Django 4.0.4 on 2023-03-29 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0018_remove_specialmeal_isspicy_specialmealship_isspicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MtPayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('pay_at', models.DateTimeField(blank=True, null=True)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('encrypt_type', models.IntegerField(default=0, null=True)),
                ('payment_method_id', models.IntegerField(default=0, null=True)),
                ('virtual_bank_id', models.IntegerField(default=0, null=True)),
                ('customer_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('sign', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.order')),
            ],
        ),
    ]
