# Generated by Django 4.0.4 on 2023-03-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0019_mtpayinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtpayinfo',
            name='status',
            field=models.IntegerField(choices=[(1, '已建立'), (2, '已付款'), (3, '已取消'), (4, '已打單'), (5, '已付款，但實際付款金額與訂單金額不符'), (6, '已付款，但付款銀行資訊不符'), (7, '已退款，付款銀行資訊不符')], default=1, null=True),
        ),
    ]
