# Generated by Django 4.0.4 on 2022-05-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0019_product_week_sum_nums_product_week_sum_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isAtm',
        ),
        migrations.AddField(
            model_name='order',
            name='CVSInfoPayFrom',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='CVSInfoPaymentNo',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='CVSInfoPaymentURL',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentType',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payinfo',
            name='CVSInfoPayFrom',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payinfo',
            name='CVSInfoPaymentNo',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payinfo',
            name='CVSInfoPaymentURL',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
