# Generated by Django 4.0.4 on 2022-05-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0021_alter_order_supervisionoffice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='CVSInfoPayFrom',
        ),
        migrations.AddField(
            model_name='order',
            name='CVSInfoExpireDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
