# Generated by Django 4.0.4 on 2022-05-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0022_remove_order_cvsinfopayfrom_order_cvsinfoexpiredate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productordership',
            name='state',
        ),
    ]
