# Generated by Django 4.0.4 on 2022-05-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0023_remove_productordership_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
