# Generated by Django 4.0.4 on 2022-05-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0024_alter_order_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
