# Generated by Django 4.0.4 on 2022-05-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0025_alter_order_createdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderMoney',
        ),
    ]
