# Generated by Django 4.0.4 on 2022-07-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0027_order_ordermoney_productordership_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prisoner_id',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prisoner_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_fee',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
