# Generated by Django 4.0.4 on 2022-09-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0028_order_prisoner_id_order_prisoner_name_order_ship_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ATMFiveDigit',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
